on:
  workflow_dispatch:
  push:
  pull_request_target:
    branches: [master]
    
  schedule:
    # UTC 17:00 -> CST (China) 1:00 see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '19 17 * * *'
    
name: Tests / test-user-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee with white list
      uses: ./.
      with:
        src: github/logep
        dst: gitee/altz
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: 'life-record,logep.github.io'
       # force_update: true
        white_list: 'life-record, logep.github.io'
        account_type: user
        timeout: 300
